server:
  port: 8081

spring:
  application:
    name: hmdp

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123456

  # Redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

  # RabbitMQ配置（Spring连接配置）
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: winston
    password: 123456
    virtual-host: /
    # 连接池配置
    listener:
      simple:
        prefetch: 1
        concurrency: 1
        max-concurrency: 5

# Jackson配置
jackson:
  default-property-inclusion: non_null

# MyBatis Plus配置
mybatis-plus:
  type-aliases-package: com.hmdp.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
    com.hmdp: debug
    org.springframework.amqp: debug