server:
  port: 8081

spring:
  application:
    name: hmdp

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123456

  # Redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

  # RabbitMQ配置（Spring连接配置）
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: winston
    password: 123456
    virtual-host: /
    # 生产者配置
    publisher-confirm-type: correlated  # 确认消息发送到交换机
    publisher-returns: true  # 开启返回模式
    template:
      mandatory: true  # 消息路由失败返回给生产者
    # 消费者配置
    listener:
      simple:
        prefetch: 1  # 每次处理1条消息
        concurrency: 1  # 最小并发数
        max-concurrency: 5  # 最大并发数
        acknowledge-mode: manual  # 手动确认消息
        retry:
          enabled: true  # 开启重试
          max-attempts: 3  # 最大重试次数
          initial-interval: 1000ms  # 重试间隔

# Jackson配置
jackson:
  default-property-inclusion: non_null

# MyBatis Plus配置
mybatis-plus:
  type-aliases-package: com.hmdp.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
    com.hmdp: debug
    org.springframework.amqp: debug